# Generated by Django 4.2.4 on 2023-08-17 16:19

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата проверки')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Отчёт о проверке')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('rejected', 'Отклонён')], max_length=8, verbose_name='Статус проверки')),
                ('sent_email', models.BooleanField(default=True, verbose_name='Email отправлен?')),
            ],
            options={
                'verbose_name': 'Проверка',
                'verbose_name_plural': 'Проверки',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=files.models.user_directory_path)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('updated', 'Обновлён'), ('accepted', 'Принят'), ('rejected', 'Отклонён')], default='new', max_length=8, verbose_name='Статус файла')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-updated_at'],
            },
        ),
    ]
